### ISSUE TITLE
Extension request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by IceWind233** [shader-slang/slang-vscode-extension#11]
I got this error and my extension does not work.
```
[Error - 11:29:01 AM] Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
	at Hd.validate (file:///d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33675)
	at new Hd (file:///d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at yt (c:\Users\zhang\.vscode\extensions\shader-slang.slang-language-extension-1.8.15-win32-x64\client\out\main.js:33:73012)
	at o (c:\Users\zhang\.vscode\extensions\shader-slang.slang-language-extension-1.8.15-win32-x64\client\out\main.js:33:48437)
	at Object.bv [as map] (c:\Users\zhang\.vscode\extensions\shader-slang.slang-language-extension-1.8.15-win32-x64\client\out\main.js:33:48523)
	at Object.zn [as asDocumentSymbols] (c:\Users\zhang\.vscode\extensions\shader-slang.slang-language-extension-1.8.15-win32-x64\client\out\main.js:33:72979)
	at u (c:\Users\zhang\.vscode\extensions\shader-slang.slang-language-extension-1.8.15-win32-x64\client\out\main.js:37:56092)
	at async OC.provideDocumentSymbols (file:///d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)
```
I tried to restart the vscode and roll back the extension to the previous version. it still does not work.

**Comment by IceWind233** [comment]
I don't know what happens it works anyway after I waiting several minutes XD
