### ISSUE TITLE
Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by pedrotrschneider** [shader-slang/slang-vscode-extension#14]
This was mentioned on #11 but the issue was marked as closed because the problem was resolved after some time.

I'm also facing the same issue on MacOS, but the problem didn't go away after some time.

VsCode output:

```
[Error - 2:57:10 PM] Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
	at Hd.validate (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33675)
	at new Hd (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at yt (/Users/{user}/.vscode/extensions/shader-slang.slang-language-extension-1.9.0-darwin-arm64/client/out/main.js:33:73012)
	at o (/Users/{user}/.vscode/extensions/shader-slang.slang-language-extension-1.9.0-darwin-arm64/client/out/main.js:33:48437)
	at Object.bv [as map] (/Users/{user}/.vscode/extensions/shader-slang.slang-language-extension-1.9.0-darwin-arm64/client/out/main.js:33:48523)
	at Object.zn [as asDocumentSymbols] (/Users/{user}/.vscode/extensions/shader-slang.slang-language-extension-1.9.0-darwin-arm64/client/out/main.js:33:72979)
	at u (/Users/{user}/.vscode/extensions/shader-slang.slang-language-extension-1.9.0-darwin-arm64/client/out/main.js:37:56092)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processImmediate (node:internal/timers:454:9)
	at async OC.provideDocumentSymbols (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)
[Error - 2:57:10 PM] Request textDocument/documentSymbol failed.
```

To add a bit more information: no syntax highlighting and no intellisense in slang files. Every time I type something in the file, this error occurs.

**Comment by pedrotrschneider** [comment]
So, I did a bit of digging, and it seems that this error happens when a file is empty. I pasted a slang shader I had somewhere and the extension started working. No clue why, tho. I'll leave the issue open because I think it warrants investigating, but feel free to close since the solution works well enough for me.

**Comment by csyonghe** [comment]
https://github.com/shader-slang/slang/pull/5842 should now fix this.

If you continue to run into this issue with the next update (v1.9.1), please file another issue with the slang code that causes the error.
